{% set version = "1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-poibin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poibin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poibin/poibin_{{ version }}.tar.gz
  sha256: 3b395e001db8f4b0a56f3645c5eef645978418baa6f8f6a7d58d9acff9f6b9eb

build:
  merge_build_host: True  # [win]
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('poibin')"           # [not win]
    - "\"%R%\" -e \"library('poibin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=poibin
  license: GPL-2
  summary: Implementation of both the exact and approximation methods for computing the cdf of
    the Poisson binomial distribution. It also provides the pmf, quantile function,
    and random number generation for the Poisson binomial distribution.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: poibin
# Type: Package
# Title: The Poisson Binomial Distribution
# Version: 1.3
# Date: 2018-05-16
# Author: Yili Hong
# Maintainer: Yili Hong <yilihong@vt.edu>
# Description: Implementation of both the exact and approximation methods for computing the cdf of the Poisson binomial distribution. It also provides the pmf, quantile function, and random number generation for the Poisson binomial distribution.
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2018-05-16 13:40:15 UTC; yilihong
# Repository: CRAN
# Date/Publication: 2018-05-16 13:58:26 UTC
