travis:
  secure:
    BINSTAR_TOKEN: c3r3yJkw75l0cMgR8DsgNizg6glHqoeqe84OLmk34RDbuuKOaQa3XMknuDIarn4nU2/H4YcLhZcM/twdjA5t6BxYt0cwPrLes1qJ53AY+k96Cg2nxFQ5n46CkDkLAzoRknXfu6rZ5OgxrJ4mKLLo3GqirlZ+9DNBbTK0IqaYXPv5Zlkat7p5t8RXwN5qvR5QuEXLJag5wbSQJtRGt+L4BUCKcqf8xuSgb8j3Pemml+9XcDzdKr1yxGLS8lwtk2VxOI8DizF9+PvjGQteFMu+e3dqGJKawpcbOvV8gNCU9/VPmwRaNhvP4Xlz/1gYUBkrkFyXND2PUkF/xhXNxnr7CvDAICYsLD9KNrGNtkHlUzE5oUw66GVfFw2RsxokZCeX0r/BvkP+zSuuAoCq9W/8+3NqWXG41vQ4psvYcHeSHCVKRxcBCN0AnElNHseaC7UDAUQi+/Ce1QPBU99NbwSydM1EHWeC+n0kTTiS+bfLQGKn7BZNCPGxYd77Uub5HJIv+Ui50deffFZ6fxNfcc+ILkiTnnut91UIsBbscBwW/6J0ErVaEKhtshlx8sEiMfORkjf6V6TofGggRJCLE7yCNNpLf+AmpLSL4ncITkiu+Sp1iOIDCsghVhFnBRZKEWIoyOCTE3ailmJxLrOsccbKJL1UV4Gfx+r9apqkOQwKxbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
